### ISSUE TITLE
F19 RSVP to-dos

### ISSUE THREAD

**Issue by monicathieu** [cu-psych-computing/cu-psych-comp-tutorial#46]
- [x] Update the Google Form to add which days people want to come @monicathieu
Send the google form to people for blasting:
- [x] Katherine & Caroline, to psych dept undergrads/post-bacs @emilynakka I think
- [x] MBBI @etedeschi
- [x] Patrick (plus other check-ins) @pab2163

**Comment by pab2163** [comment]
sent to patrick

**Comment by emilynakka** [comment]
Sorry if I'm missing it on here, but I don't see the URL for the form. Could someone please send it to me, and then I'll send to Katherine/Caroline? Thanks!

**Comment by monicathieu** [comment]
Sorry, link for survey takers is here! https://forms.gle/SCStmii85GYqBVsM6

**Comment by emilynakka** [comment]
Thanks! Just sent to Katherine/Caroline.

**Comment by monicathieu** [comment]
Marked @etedeschi 's MBBI blast to-do as done bc we are receiving enough form submissions endorsing MBBI affiliation that it looks like it must have been sent!
