### ISSUE TITLE
fix links on programming, part 1

### ISSUE THREAD

**Issue by mvantieghem** [cu-psych-computing/cu-psych-comp-tutorial#52]
If I go to any individual html for tomorrow's Part 1 materials, the links to the other 2 tutorial htmls are broken. 

links to all 3 tutorials from the main github page work fine.

**Comment by monicathieu** [comment]
Ahh thanks for flagging! Yeah since we moved stuff into R/ and Python/ folders I think some of my old links broke. will fix
