### ISSUE TITLE
Redo website rendering with blogdown?

### ISSUE THREAD

**Issue by monicathieu** [cu-psych-computing/cu-psych-comp-tutorial#58]
The original website has been done with the Carpentries' workshop website template, which uses Jekyll as its static site rendering engine. While this engine works well for the Carpentries' needs, some of the features seem a bit unwieldy for our needs. For example:

- It has a lot of software dependencies that are JUST jekyll-related, and seem to be popping up security issues on GitHub frequently enough to be of concern
- There is no easy path to render R Markdown tutorial pages using the unified website template. Everything we do outside of the Carpentries episode structure currently has to be hard linked
- To the above, blogdown is just much more R-specific, which might be nice since most of our lessons are published via R Markdown. Blogdown is also flexible to publish non-blogdown-rendered pages when applicable, although in those cases (say, python notebooks rendered directly to html) NO static site renderer that I know of can reformat those htmls with website theme. So that's not a blogdown problem

Anyway, the current website WORKS, so this isn't a super time-sensitive issue, but worth considering.

**Comment by monicathieu** [comment]
Subsumes issue #48 , which was pondering whether to get people to write their lessons in Jekyll-safe format, to get lesson Rmds to auto-render every time we "knit" the entire website. If we transfer the website to Hugo (via blogdown) instead of Jekyll, we get the lesson auto-formatting for free. Clearly I've been wanting this functionality for a while!

**Comment by emilynakka** [comment]
I can make this change. I weirdly love doing this kind of work.

**Comment by monicathieu** [comment]
That would be great! It MIGHT end up being a bit involved, but if you've set up a `blogdown` website before it's not that bad. I suspect that migrating this website over would involve:

1. Selecting a blogdown/Hugo theme that works with Bootstrap (I mainly want toc_float to work in our lessons)
1. Translating the home page template from Jekyll-speak to Hugo-speak
1. Translating the workshop landing page template from Jekyll-speak to Hugo-speak
1. Reorganizing the lesson folders into blogdown's expected blog post folder structure
1. Other stuff I haven't thought of 🙃 
1. Once everything is done, deleting the Jekyll helper files in the repo

My hunch is that translating the homepage and workshop landing page will take the longest, since those require HTML-type recoding, but I don't know how long for sure!

**Comment by emilynakka** [comment]
All good! I've done plenty of web development work in my previous life and although I haven't used Hugo/blogdown specifically, I've created websites using RMarkdown's built-in functionality (that works with Bootstrap) and have played around a bit with Jekyll in planning updates for the current site. (I also did some googling on Jekyll to Hugo conversions this afternoon, and it looks quite straightforward.) Based on all of this, I'm feeling good about proceeding.

**Comment by emilynakka** [comment]
Oh no!

<img width="1232" alt="Screen Shot 2020-08-25 at 3 48 01 PM" src="https://user-images.githubusercontent.com/36014646/91220580-60dc2f80-e6ea-11ea-9478-87ecb3df1edf.png">

I'm not sure I know how to fix this (or why it isn't working when our local instances did). @monicathieu, any ideas?

**Comment by emilynakka** [comment]
Actually, I think answers are here: https://bookdown.org/yihui/blogdown/github-pages.html

I can jump on this quickly now, but I will need to leave in 15 mins for a meeting with Tory. Can pick back up first thing tomorrow, as the Tory meetings usually run long!

**Comment by monicathieu** [comment]
Yeah, that pretty much summarizes the issue.

The easiest way I've found to get around this is to use the instructions [here](https://gist.github.com/cobyism/4730490) to make the gh-pages branch a subtree of a different default branch, and just use the git subtree push command once every time we make a big change on the master branch. I'll duplicate the gh-pages branch to another branch and make that one the master branch, so we can use the subtree push strategy on the gh-pages branch.

**Comment by monicathieu** [comment]
Ok, branch duplicated and `master` reset as the default branch. Ready for whoever to subtree push!

**Comment by emilynakka** [comment]
Although I could follow the instructions on that page for a subtree push, I'm not sure I am completely following (subtrees are new to me!). Would you be comfortable pushing this time and I'll do some reading to make sure I understand how this all is working the next time we make a change?

**Comment by monicathieu** [comment]
I'm no subtree wizard either, I've only really used them on my blogdown personal website! I will take care of this one (it looks to be hiccuping slightly because the gh-pages branch has had other changes on it in the past) but then we should be smooth to use the master branch as the default branch doing forward.

**Comment by monicathieu** [comment]
All righty, **subtree creation is complete, synced with GitHub, and THE WEBSITE WORKS!!!**

The `master` branch is again the default branch and _do not touch the `gh-pages` branch unless you are subtree pushing._

I THINK it will sync correctly to your computer if you pull all my changes down, but to update the website in the future:

1. Make changes on side branch if big changes, or master branch if small changes that are safe to make directly on master
1. Blogdown serve site on whatever local branch
1. Sync changes to master when approved, if applicable
1. Locally, check out master branch, then `git subtree push --prefix public origin gh-pages` to update the gh-pages branch from the master branch

And that should do it in the future!

All future website cleanup items can be done under a different issue since blogdown is officially set up. WE CAN CLOSE THIS.
