### ISSUE TITLE
Subtree Push Error

### ISSUE THREAD

**Issue by emilynakka** [cu-psych-computing/cu-psych-comp-tutorial#66]
I noticed that the links on the new Home and Workshop pages weren't updated after moving the tutorial content from /static to /content, so I pushed the quick fixes to the master branch in hopes of attempting the new subtree push. However, I received the following error when trying to run the subtree push code:

**What I tried to run:**
`git subtree push --prefix public origin gh-pages`

**What I got back:**
`git push using:  origin gh-pages
Counting objects: 49, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (49/49), 38.00 KiB | 7.60 MiB/s, done.
Total 49 (delta 25), reused 7 (delta 3)
remote: Resolving deltas: 100% (25/25), completed with 21 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/cu-psych-computing/cu-psych-comp-tutorial.git
 ! [remote rejected] 297acbd3a652fb0a291f471dd48d25101d9615a0 -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cu-psych-computing/cu-psych-comp-tutorial.git'
`

In order to make these changes, do I need to initiate a pull request? Or something else? @monicathieu, sorry to bother you again, but I'm hoping to sort this out so I can figure out how to do this once and for all!

**Comment by monicathieu** [comment]
This MIGHT have been a permissions issue. I just upgraded your repo permissions to Write instead of Maintain—if you try the same command again is the error different (or ideally resolved)?

**Comment by emilynakka** [comment]
Unfortunately it's the same:
`git push using:  origin gh-pages
Counting objects: 49, done.
Delta compression using up to 8 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (49/49), 38.00 KiB | 7.60 MiB/s, done.
Total 49 (delta 25), reused 7 (delta 3)
remote: Resolving deltas: 100% (25/25), completed with 21 local objects.
remote: error: GH006: Protected branch update failed for refs/heads/gh-pages.
remote: error: At least 1 approving review is required by reviewers with write access.
To https://github.com/cu-psych-computing/cu-psych-comp-tutorial.git
 ! [remote rejected] 297acbd3a652fb0a291f471dd48d25101d9615a0 -> gh-pages (protected branch hook declined)
error: failed to push some refs to 'https://github.com/cu-psych-computing/cu-psych-comp-tutorial.git'`

No need to sort this out this evening, as I doubt anyone will be looking at the links tonight. Either way, thanks as always for your help!

**Comment by monicathieu** [comment]
I THINK it was another permissions issue, hopefully resolved now--try the same command once more (with feeling)?

Your error message led me to [GitHub's docs](https://docs.github.com/en/github/administering-a-repository/configuring-protected-branches), which made me realize that because `gh-pages` was the old default branch, it still had branch protections that I turned on for the default branch a while ago. Now that we are switching back to the old format, where `master` is the default branch and `gh-pages` should never have edits made directly on it, I put `master` under branch protection and removed `gh-pages` so force-pushing should be allowed now. Let me know!

**Comment by emilynakka** [comment]
That solved the subtree push error! Hurrah.

Unfortunately, the relative links are working differently now that things are up and running on GitHub pages than they did on my local instance, as GH pages seems to treat the `/public` folder as the root. Gah. I'll fix these in a larger set of website housekeeping updates on a dedicated branch, as I see that other relative links (e.g., within some of the tutorials) aren't working.
