### ISSUE TITLE
Bring Python tutorials into Hugo/blogdown

### ISSUE THREAD

**Issue by emilynakka** [cu-psych-computing/cu-psych-comp-tutorial#69]
Currently the Python tutorials live in `/static`, so the site's navigation and formatting aren't applied to them. For my future reference, here are some links that could be helpful in accomplishing this:

https://www.timlrx.com/2018/03/25/uploading-jupyter-notebook-files-to-blogdown/

https://juanitorduz.github.io/pelican_to_blogdown/

https://github.com/rstudio/blogdown/issues/277

https://www.shenxt.info/post/blogdown-instruction/

https://statslab.eighty20.co.za/posts/blogging_from_jupyter/

https://github.com/rstudio/blogdown/issues/262

**Comment by monicathieu** [comment]
It looks like using `nbconvert` to render .ipynb files as .md files (per a few of the links you found) is gonna be the way to go.

I think if the repo is set up with code in `R/build.R` to call `nbconvert` on every .ipynb file that's newer than its paired .md file (per the [blogdown manual](https://bookdown.org/yihui/blogdown/methods.html#methods)), then `blogdown::serve_site()` or `build_site()` will render all the Rmds (as usual), then call custom code to render the Python notebooks, then write all .md files to HTML.

Python notebook writers will have to be sure to run-all their notebooks before saving, to make sure the chunk output shows up properly before converting to Markdown. So it's not a fully automated option, but definitely seems feasible.

**Comment by emilynakka** [comment]
Thanks for your feedback! I'll plan to proceed with that option.
