### ISSUE TITLE
Review and update Day 3 content

### ISSUE THREAD

**Issue by emilynakka** [cu-psych-computing/cu-psych-comp-tutorial#73]
Opening this issue for Day 3 (Python) workshop updates. It seems like #54 hasn't been addressed yet; flagging it here in case it should be part of these updates!

I'll add assignees as soon as we confirm Day 3 staffing.

**Comment by boomsbloom** [comment]
I just made some changes to lessons 3 and 4 of the python workshop--those should be good to go!

**Comment by emilynakka** [comment]
Thanks so much, Jonathan! I've just made some minor formatting tweaks across all the Python tutorials to ensure consistency (e.g., capitalization, formatting the names of modules, etc.). I'm going to submit a pull request now, as I think everything is looking great!
