### ISSUE TITLE
paul to-dos for interaval workshop

### ISSUE THREAD

**Issue by pab2163** [cu-psych-computing/cu-psych-comp-tutorial#86]
- [x] add 'mountain' analogy for for explaining ML vs. numerical estimation of intervals
- [x] flesh out MCMC slide
- [x] illustrate 'what does your interval represent' on slide 14/15 using example dataset
- [x] make slides on the analysis of the datasets (t-test, regression, regression with covariate, boostrap, bayesian)

**Comment by monicathieu** [comment]
To be done on the `march2021` branch. Note to selves: yoke this issue to the appropriate pull request when ready
